fix: can not run bechmark in MacOS (#77)
This patch fix can not run benchmark on MacOS
error 

```cli
thread 'main' panicked at benchmark/src/bin/clickbench_client.rs:461:51:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
for the reason that for some os its "lo0" instead of "lo"

more detail:

https://www.ibm.com/docs/en/was-nd/8.5.5?topic=machines-aliasing-network-interface-card-loopback-device

---------

Signed-off-by: yihong0618 <zouzou0208@gmail.com>